name: quran_with_tafsir
description: >-
  Offline Quran package for Dart with Arabic text, English translation,
  Tafsir Al-Muyassar, page/juz navigation, search, and audio URLs.
version: 1.0.1
homepage: https://github.com/mo-amir99/quran_with_tafsir
repository: https://github.com/mo-amir99/quran_with_tafsir
issue_tracker: https://github.com/mo-amir99/quran_with_tafsir/issues

topics:
  - quran
  - islam
  - tafsir
  - arabic

environment:
  sdk: ">=3.0.0 <4.0.0"
